sudo: required
language: c++
dist: trusty

compiler:
  - clang

before_install:
  - sudo apt-get install cmake

script:
  - mkdir build
  - cd build
  - cmake -D USE_ITK=OFF -D BUILD_CLI=ON ../src
  - make
  - ctest
