language: c++
dist: trusty

compiler:
  - clang
  - gcc

script:
  - mkdir build
  - cd build
  - cmake -D USE_ITK=OFF -D BUILD_CLI=ON ../src
  - make
  - ctest

notifications:
  slack: sciinstitute:lZnpQQXNd4Io5iGDPQDpJmI1
